package journeyjourney.journey.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tbl_collection", "id", Collection.class);
		arp.addMapping("tbl_comments", "id", Comments.class);
		arp.addMapping("tbl_follow", "id", Follow.class);
		arp.addMapping("tbl_food", "id", Food.class);
		arp.addMapping("tbl_imgs", "id", Imgs.class);
		arp.addMapping("tbl_journeyonline", "id", Journeyonline.class);
		// Composite Primary Key order: note_id,tel
		arp.addMapping("tbl_love", "note_id,tel", Love.class);
		arp.addMapping("tbl_modle", "id", Modle.class);
		arp.addMapping("tbl_note", "note_id", Note.class);
		arp.addMapping("tbl_online_travel", "id", OnlineTravel.class);
		arp.addMapping("tbl_plan", "id", Plan.class);
		arp.addMapping("tbl_route", "id", Route.class);
		arp.addMapping("tbl_son_comment", "id", SonComment.class);
		arp.addMapping("tbl_tag", "tag_id", Tag.class);
		arp.addMapping("tbl_user", "tel", User.class);
	}
}

