package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseCollection;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Collection extends BaseCollection<Collection> {
	public static final Collection dao = new Collection().dao();
}
