package journeyjourney.journey.model;

import java.util.List;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Db;

import journeyjourney.journey.model.base.BaseComments;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Comments extends BaseComments<Comments> {
	public static final Comments dao = new Comments().dao();

	/**
	 * 评论
	 * @param note_id
	 * @param comments_content
	 * @param tel
	 * @param comments_time
	 * @return
	 */
    public String oneComment(String note_id, String comments_content, String tel, String comments_time) {
        boolean b =new Comments().set("note_id",note_id).set("comments_content",comments_content).set("tel",tel).set("comments_time",comments_time).save();

        if(b) {
            Note note = Note.dao.findFirst("select * from tbl_note where note_id = ?",note_id);
            int n = Integer.parseInt(note.getStr("comments_num"));
            Note.dao.findById(note_id).set("comments_num",++n).update();
            return n+"";
        }else {
            return "false";
        }
    }

    /**
     * 展示评论
     * @param note_id
     * @return
     */
    public String showComment(String note_id) {
        JSONObject jsonObject = new JSONObject();
        JSONArray jarray = new JSONArray();
        List<Comments> lists = Comments.dao.find("select * from tbl_comments where note_id = ? limit 0,10",note_id);
        for(Comments comment : lists) {
            

            int total = Db.queryInt("select count(*) from tbl_son_comment where parentId = ?",comment.getStr("id"));
            JSONObject jObject = new JSONObject();
            
            jObject.put("sonCount",total);
  
            jObject.put("id",comment.getStr("id"));
            
            jObject.put("comments_content",comment.getStr("comments_content"));

            jObject.put("comments_time",comment.getStr("comments_time"));
            //用户信息
            String tel = comment.getStr("tel");
            User user = User.dao.findByIdLoadColumns(tel,"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            
            jObject.put("userName",userName);
            jObject.put("userHeadSrc",userHeadSrc);
            
            jarray.add(jObject);
        }
        jsonObject.put("array",jarray);
        return jsonObject.toString();
    }

    /**
     * 展示子评论
     * @param parentId
     * @return
     */
    public String showSonComment(String parentId) {
        JSONObject jsonObject = new JSONObject();
        JSONArray jarray = new JSONArray();
       
        List<SonComment> lists = SonComment.dao.find("select * from tbl_son_comment where parentId = ? limit 0,10",parentId);

        for(SonComment sonComment : lists) {
            JSONObject jObject = new JSONObject();
  
            jObject.put("id",sonComment.getStr("id"));
            
            jObject.put("comments_content",sonComment.getStr("comments_content"));

            jObject.put("comments_time",sonComment.getStr("comments_time"));
            //用户信息
            String tel = sonComment.getStr("tel");
            User user = User.dao.findByIdLoadColumns(tel,"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            
            
            jObject.put("userName",userName);
            jObject.put("userHeadSrc",userHeadSrc);
            
            jarray.add(jObject);
        }
        jsonObject.put("array",jarray);
        return jsonObject.toString();

    }

    /**
     * 写子评论
     * @param note_id
     * @param parentId
     * @param comments_content
     * @param tel
     * @param comments_time
     * @return
     */
    public String oneSonComment(String note_id, String parentId, String comments_content, String tel,
            String comments_time) {
        boolean b =new SonComment().set("parentId",parentId).set("comments_content",comments_content).set("tel",tel).set("comments_time",comments_time).save();
        
        Note note = Note.dao.findFirst("select * from tbl_note where note_id = ?",note_id);
        int n = Integer.parseInt(note.getStr("comments_num"));
        Note.dao.findById(note_id).set("comments_num",++n).update();
        
        if(b) {
            return "true";
        }else {
            return "false";
        }
    }


    
    
    
    
    
    
    
}
