package journeyjourney.journey.model;

import java.util.List;

import journeyjourney.journey.model.base.BaseFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	public static final Follow dao = new Follow().dao();

	/**
	 * 展示我的关注列表
	 * @param tel
	 * @return
	 */
    public String showMyFollows(String tel) {
        List<Follow> lists = Follow.dao.find("select * from tbl_follow where fans_tel = ?",tel);
        StringBuffer buffer0 = new StringBuffer();
        StringBuffer buffer1 = new StringBuffer();
        for(Follow follow : lists) {
            String follow_tel = follow.getStr("follow_tel");
            User user = User.dao.findFirst("select * from tbl_user where tel = ?",follow_tel);
            String headSrc =  "userImg/" + user.getStr("headSrc");         
            
            buffer0.append(follow_tel);
            buffer0.append(",");
            
            buffer1.append(headSrc);
            buffer1.append(",");
        }
        String str = buffer0 +"&&&"+ buffer1;
        return str;
    }
}
