package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseFood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Food extends BaseFood<Food> {
	public static final Food dao = new Food().dao();
}
