package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseImgs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Imgs extends BaseImgs<Imgs> {
	public static final Imgs dao = new Imgs().dao();
}
