package journeyjourney.journey.model;

import java.util.ArrayList;
import java.util.List;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;

import journeyjourney.journey.model.base.BaseJourneyonline;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Journeyonline extends BaseJourneyonline<Journeyonline> {
	public static final Journeyonline dao = new Journeyonline().dao();

    /**
     * 线上旅游页面
     * @param tel
     * @return
     */
    public String journeyOnline() {
        List<Journeyonline> lists = new ArrayList<Journeyonline>();
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();
        String str1 = "select * from tbl_journeyonline";
        List<Journeyonline> journeys = Journeyonline.dao.find(str1);
        for(Journeyonline journey : journeys) {
            JSONObject jsonObj = new JSONObject();
            String title = journey.getStr("title");
            String introduce = journey.getStr("introduce");
            String image = journey.getStr("image");
            String image_one = journey.getStr("image_one");
            String image_two = journey.getStr("image_two");
            String image_three = journey.getStr("image_three");
            String address_one = journey.getStr("address_one");
            String address_two = journey.getStr("address_two");
            String address_three = journey.getStr("address_three");
            String info_one = journey.getStr("introduce_one");
            String info_two = journey.getStr("introduce_two");
            String info_three = journey.getStr("introduce_three");
            jsonObj.put("title", title);
            jsonObj.put("introduce", introduce);
            jsonObj.put("image", image);
            jsonObj.put("image_one",image_one);
            jsonObj.put("image_two",image_two);
            jsonObj.put("image_three",image_three);
            jsonObj.put("introduce_one",info_one);
            jsonObj.put("introduce_two",info_two);
            jsonObj.put("introduce_three",info_three);
            jsonObj.put("address_one",address_one);
            jsonObj.put("address_two",address_two);
            jsonObj.put("address_three",address_three);
            jArray.add(jsonObj);
        }
        jobj.put("array", jArray);   
        return jobj.toString();
    }

}
