package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseLove;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Love extends BaseLove<Love> {
	public static final Love dao = new Love().dao();
}
