package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseModle;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Modle extends BaseModle<Modle> {
	public static final Modle dao = new Modle().dao();
}
