package journeyjourney.journey.model;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Db;

import journeyjourney.journey.model.base.BaseNote;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Note extends BaseNote<Note> {
	public static final Note dao = new Note().dao();
	
	   /**
     * 首页展示
     * @return
     */
    public String homeInterface(String tel) {
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();

        String str1 = "select * from tbl_note limit 0,10";
        List<Note> notes = Note.dao.find(str1);
        for(Note noteee : notes) {

            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            
            //9图信息
            List<Imgs> imgs = Imgs.dao.find("select * from tbl_imgs where node_id = '"+noteId+"'");
            StringBuffer buffer = new StringBuffer();
            buffer.append("");
            for(Imgs img : imgs) {
                buffer.append("smallImgs/" + img.getStr("img_src")+",");
            }
            List<Comments> comments = Comments.dao.find("select * from tbl_comments where note_id = '"+noteId+"' order by comments_time desc  limit 0,2 ");
            String twoComments = "";
            for(Comments com : comments) {
                String comment = com.getStr("comments_content");
                String commentTel = com.getStr("tel");
                String commentdata = com.getStr("comments_time");
                twoComments = twoComments + "&&&" + comment + "%%" + commentTel + "%%" + commentdata;
            }
            
            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            //笔记信息
            jsonObj.put("note_id",noteee.getStr("note_id"));
            jsonObj.put("res_type",noteee.getStr("res_type")); 
            jsonObj.put("cover_src","coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jsonObj.put("collection_num", noteee.getStr("collection_num"));
            jsonObj.put("comments_num", noteee.getStr("comments_num"));
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("upload_time", noteee.getStr("upload_time"));
            //9图
            jsonObj.put("nineSrc", buffer);
            //评论
            jsonObj.put("twoComments", twoComments);
     
            //是否点赞
            Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(love!=null) {
                jsonObj.put("isLove",1);
            }else {
                jsonObj.put("isLove",0);
            }
            //是否收藏
            Collection collection = Collection.dao.findFirst("select * from tbl_collection where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(collection!=null) {
                jsonObj.put("isCollection",1);
            }else {
                jsonObj.put("isCollection",0);
            }
            jArray.add(jsonObj);
        }
            
        jobj.put("array", jArray);      
        return jobj.toString();
    }

    
    /**
     * 搜索框
     * @param tel
     * @param param
     * @return
     */
    public String searchInterface(String tel, String param) {
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();

        String sql ="select *from (select tbl_note.*,tbl_user.name from tbl_note,tbl_user where tbl_note.tel = tbl_user.tel )t where titlle like '%"+param+"%' or upload_position like '%"+param+"%' or name like '%"+param+"%'\n" + 
                "";

        
        List<Note> notes = Note.dao.find(sql);
        for(Note noteee : notes) {

            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            
            //9图信息
            List<Imgs> imgs = Imgs.dao.find("select * from tbl_imgs where node_id = '"+noteId+"'");
            StringBuffer buffer = new StringBuffer();
            buffer.append("");
            for(Imgs img : imgs) {
                buffer.append("smallImgs/" + img.getStr("img_src")+",");
            }
            List<Comments> comments = Comments.dao.find("select * from tbl_comments where note_id = '"+noteId+"' order by comments_time desc  limit 0,2 ");
            String twoComments = "";
            for(Comments com : comments) {
                String comment = com.getStr("comments_content");
                String commentTel = com.getStr("tel");
                String commentdata = com.getStr("comments_time");
                twoComments = twoComments + "&&&" + comment + "%%" + commentTel + "%%" + commentdata;
            }
            
            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            //笔记信息
            jsonObj.put("note_id",noteee.getStr("note_id"));
            jsonObj.put("cover_src","coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jsonObj.put("collection_num", noteee.getStr("collection_num"));
            jsonObj.put("comments_num", noteee.getStr("comments_num"));
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("upload_time", noteee.getStr("upload_time"));
            //9图
            jsonObj.put("nineSrc", buffer);
            //评论
            jsonObj.put("twoComments", twoComments);
     
            //是否点赞
            Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(love!=null) {
                jsonObj.put("isLove",1);
            }else {
                jsonObj.put("isLove",0);
            }
            //是否收藏
            Collection collection = Collection.dao.findFirst("select * from tbl_collection where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(collection!=null) {
                jsonObj.put("isCollection",1);
            }else {
                jsonObj.put("isCollection",0);
            }
            jArray.add(jsonObj);
        }
            
        jobj.put("array", jArray);      
        return jobj.toString();
    }
    
    
    /**
     * 关注页
     * @param tel
     * @param count
     * @return
     */
    public String followInterface(String tel,String count) { 
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();

        String str1 = "select * from tbl_note where tel in (select follow_tel from tbl_follow where fans_tel = '"+tel+"') order by upload_time desc  limit "+count+",5";
        List<Note> notes = Note.dao.find(str1);
        for(Note noteee : notes) {
            
            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userTel = user.getStr("tel");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            
            //9图信息
            List<Imgs> imgs = Imgs.dao.find("select * from tbl_imgs where node_id = '"+noteId+"'");
            StringBuffer buffer = new StringBuffer();
            for(Imgs img : imgs) {
                buffer.append("smallImgs/" + img.getStr("img_src")+",");
            }
            if(buffer.length()==0) {
                buffer.append("1");
            }
            List<Comments> comments = Comments.dao.find("select * from tbl_comments where note_id = '"+noteId+"' order by comments_time desc  limit 0,2 ");
            String twoComments = "";
            for(Comments com : comments) {
                String comment = com.getStr("comments_content");
                String commentTel = com.getStr("tel");
                String commentdata = com.getStr("comments_time");
                twoComments = twoComments + "&&&" + comment + "%%" + commentTel + "%%" + commentdata;
            }
            
            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            jsonObj.put("userTel", userTel);
            
            //笔记信息
            jsonObj.put("note_id",noteee.getStr("note_id"));
            jsonObj.put("cover_src","coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("res_type",noteee.getStr("res_type"));         
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jsonObj.put("collection_num", noteee.getStr("collection_num"));
            jsonObj.put("comments_num", noteee.getStr("comments_num"));
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("upload_time", noteee.getStr("upload_time"));
            //9图
            jsonObj.put("nineSrc", buffer);
            //评论
            jsonObj.put("twoComments", twoComments);
     
            //是否点赞
            Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(love!=null) {
                jsonObj.put("isLove",1);
            }else {
                jsonObj.put("isLove",0);
            }
            //是否收藏
            Collection collection = Collection.dao.findFirst("select * from tbl_collection where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(collection!=null) {
                jsonObj.put("isCollection",1);
            }else {
                jsonObj.put("isCollection",0);
            }
            jArray.add(jsonObj);
        }
        if(jArray.size()==0) {
            return "1";
        }else {
            jobj.put("array", jArray);      
        }
        
        return jobj.toString();
    }
    
    /**
     * 推荐页面
     * @param tel
     * @return
     */
    public String recommendInterface(String tel,String count) {
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();
        String str1 = "select * from tbl_note order by like_num desc  limit "+count+",10";
        List<Note> notes = Note.dao.find(str1);
        for(Note noteee : notes) {
            String userTel = noteee.getStr("tel");
            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");

            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            jsonObj.put("userTel", userTel);
            //笔记信息
            jsonObj.put("cover_src",  "coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("res_type",noteee.getStr("res_type"));    
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jsonObj.put("note_id", noteId);
            //是否点赞
            Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+noteId+"' and tel = '"+tel+"'");
            if(love!=null) {
                jsonObj.put("isLove",1);
            }else {
                jsonObj.put("isLove",0);
            }

            jArray.add(jsonObj);
        }
        if(jArray.size()==0) {
            return "1";
        }else {
            jobj.put("array", jArray);      
        }
        return jobj.toString();
    }

    /**
     * 同城
     * @param city
     * @param tel
     * @return
     */
    public String sameCityInterface(String city,String tel,String count) {
        List<Note> lists = new ArrayList<Note>();
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();
        List<Note> notes = Note.dao.find("select * from tbl_note where upload_position like '%"+city+"%' limit "+count+",10");
        for(Note noteee : notes) {
            String userTel = noteee.getStr("tel");
            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            jsonObj.put("userTel", userTel);
            //笔记信息
            jsonObj.put("res_type",noteee.getStr("res_type"));    
            jsonObj.put("cover_src",  "coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jsonObj.put("note_id", noteee.getStr("note_id"));
            //是否点赞
            Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+noteee.getStr("note_id")+"' and tel = '"+tel+"'");
            if(love!=null) {
                jsonObj.put("isLove",1);
            }else {
                jsonObj.put("isLove",0);
            }
            
            jArray.add(jsonObj);
        }
        if(jArray.size()==0) {
            return "1";
        }else {
            jobj.put("array", jArray);      
        }
        return jobj.toString();
    }

    /**
     * 详情页
     * @param note_id
     * @param tel
     * @return
     */
    public String detailsInterface(String note_id,String tel) {
        JSONObject jobj = new JSONObject();
        Note note  = Note.dao.findById(note_id);
        //用户信息

        User user111 = User.dao.findByIdLoadColumns(tel,"name,headSrc");
        String userName111 = user111.getStr("name");
        String userHeadSrc111 = "userImg/" + user111.getStr("headSrc");
        
        
        jobj.put("myUserName",userName111);
        jobj.put("myUserHeadSrc",userHeadSrc111);
        
        
        jobj.put("note_id",note.getStr("note_id"));
        //手机号
        jobj.put("tel",note.getStr("tel"));
        //用户信息
        User user = User.dao.findByIdLoadColumns(note.getStr("tel"),"name,headSrc");
        String userName = user.getStr("name");
        String userHeadSrc = "userImg/" + user.getStr("headSrc");
        //用户信息
        jobj.put("userName", userName);
        jobj.put("userHeadSrc", userHeadSrc);   
        jobj.put("cover_src", "coverImg/"+ note.getStr("cover_src")); 
        jobj.put("like_num",note.getStr("like_num"));
        jobj.put("collection_num",note.getStr("collection_num"));     
        jobj.put("comments_num",note.getStr("comments_num"));
        jobj.put("titlle",note.getStr("titlle"));
        jobj.put("content",note.getStr("content"));
        jobj.put("upload_time",note.getStr("upload_time"));
        jobj.put("upload_position",note.getStr("upload_position"));
        jobj.put("res_type",note.getStr("res_type"));
        jobj.put("modle_id",note.getStr("modle_id"));
        
//        Tag tag = Tag.dao.findByIdLoadColumns(note.getStr("tag_id"),"tag_name");
//        String tag_name = tag.getStr("tag_name");
//        jobj.put("tag_name",tag_name);
        
        //9图信息
        List<Imgs> imgs = Imgs.dao.find("select * from tbl_imgs where node_id = '"+note_id+"'");
        StringBuffer buffer = new StringBuffer();
        buffer.append("");
        for(Imgs img : imgs) {
            buffer.append("smallImgs/" + img.getStr("img_src")+",");
        }
        jobj.put("nineSrc",buffer);

         
        //是否关注此人
        Follow follow = Follow.dao.findFirst("select * from tbl_follow where fans_tel = '"+tel+"' and follow_tel = '"+note.getStr("tel")+"'");
        if(follow!=null) {
            jobj.put("isFollow",1);
        }else {
            jobj.put("isFollow",0);
        }
        //是否点赞
        Love love = Love.dao.findFirst("select * from tbl_love where note_id = '"+note_id+"' and tel = '"+tel+"'");
        if(love!=null) {
            jobj.put("isLove",1);
        }else {
            jobj.put("isLove",0);
        }
        //是否收藏
        Collection collection = Collection.dao.findFirst("select * from tbl_collection where note_id = '"+note_id+"' and tel = '"+tel+"'");
        if(collection!=null) {
            jobj.put("isCollection",1);
        }else {
            jobj.put("isCollection",0);
        }
        //评论
        JSONArray jarray = new JSONArray();
        List<Comments> lists = Comments.dao.find("select * from tbl_comments where note_id = ? limit 0,10",note_id);
        for(Comments comment : lists) {
            JSONObject jObject = new JSONObject();
  
            int total = Db.queryInt("select count(*) from tbl_son_comment where parentId = ?",comment.getStr("id"));
            jObject.put("sonCount",total);
            
            jObject.put("id",comment.getStr("id"));
            
            jObject.put("comments_content",comment.getStr("comments_content"));

            jObject.put("comments_time",comment.getStr("comments_time"));
            //用户信息
            String tel000 = comment.getStr("tel");
            User user000 = User.dao.findByIdLoadColumns(tel,"name,headSrc");
            String userName000 = user000.getStr("name");
            String userHeadSrc000 = "userImg/" + user000.getStr("headSrc");
            
            jObject.put("userName",userName000);
            jObject.put("userHeadSrc",userHeadSrc000);
            
            jarray.add(jObject);
        }
        jobj.put("array",jarray);

        return jobj.toString();
    }

    /**
     * 关注
     * @param fans_tel
     * @param follow_tel
     * @return
     */
    public String detailsInterfaceFollow(String fans_tel, String follow_tel) {
        
        boolean flag = new Follow().set("fans_tel",fans_tel).set("follow_tel",follow_tel).save();
        if(flag) {
            return 1+"";
        }else {
            return "false";
        }
        
    }
    
    /**
     * 取消关注
     * @param fans_tel
     * @param follow_tel
     * @return
     */
    public String detailsInterfaceCancelFollow(String fans_tel, String follow_tel) {
        String sql = "delete from tbl_follow where fans_tel = '"+fans_tel+"' and follow_tel = '"+follow_tel+"'";
        int flag = Db.update(sql);
        if(flag>0) {
            return 0+"";
        }else {
            return "false";
        }
    }

    /**
     * 点赞
     * @param fans_tel
     * @param note_id
     * @return
     */
    public String followInterfaceLove(String tel, String note_id) {
        boolean flag = new Love().set("note_id",note_id).set("tel",tel).save();
        if(flag) {
            Note note = Note.dao.findByIdLoadColumns(note_id,"like_num");
            int count = Integer.parseInt(note.getStr("like_num"));
            Note.dao.findById(note_id).set("like_num",++count).update();
            return "1";
        }else {
            return "false";
        }
    }

    /**
     * 取消点赞
     * @param fans_tel
     * @param note_id
     * @return
     */
    public String followInterfaceCancelLove(String tel, String note_id) {
        String sql = "delete from tbl_love where note_id = '"+note_id+"' and tel = '"+tel+"'";

        int flag = Db.update(sql);
        if(flag>0) {
            Note note = Note.dao.findByIdLoadColumns(note_id,"like_num");
            int count = Integer.parseInt(note.getStr("like_num"));
            if(count>0) {
                Note.dao.findById(note_id).set("like_num",--count).update();
            }
            
            return "0";
        }else {
            return "false";
        }
    }
    
    /**
     * 展示收藏夹
     * @param tel
     * @return
     */
    public String ShowCollectionDirectory(String tel) {
        List<Collection> dirs =  Collection.dao.find("select * from tbl_collection where tel = '"+tel+"'");
        StringBuffer buffer = new StringBuffer();
        for(Collection col : dirs) {
            String name = col.getStr("name");
            buffer.append(name);
            buffer.append(",");
            }
        if(buffer.length()==0) {
            buffer.append("false");
        }
        return buffer+"";
    }
    
    /**
     * 添加收藏夹
     * @param tel
     * @param dir
     * @return
     */
    public String addCollectionDirectory(String tel, String name) {
        Collection col = Collection.dao.findFirst("select * from tbl_collection where tel = ? and name = ?",tel,name);
        if(col == null) {
            boolean b= new Collection().set("tel",tel).set("name",name).save();
            return b+"";
        }else {
            return "该收藏夹已存在";
        }
        
        
    }

    /**
     * 展示某个收藏夹里所有笔记
     * @param tel
     * @param name
     * @return
     */
    public String showOneDiretrory(String tel, String name) {
        List<Collection> collections = Collection.dao.find("select * from tbl_collection where tel = ? and name = ?",tel,name);
        JSONObject jsonOjb = new JSONObject();
        JSONArray jarray = new JSONArray();
        for(Collection col : collections) {
            String note_id = col.getStr("note_id");
            if(note_id!=null) {
                JSONObject jobj = new JSONObject();
                Note note = Note.dao.findFirst("select * from tbl_note where note_id = '"+note_id+"'");
                jobj.put("note_id",note_id);
                jobj.put("tel",note.getStr("tel"));                
                jobj.put("cover_src", "coverImg/"+ note.getStr("cover_src"));                
                jobj.put("like_num",note.getStr("like_num"));                
                jobj.put("collection_num",note.getStr("collection_num"));                
                jobj.put("comments_num",note.getStr("comments_num"));             
                jobj.put("titlle",note.getStr("titlle"));              
                jobj.put("content",note.getStr("content"));          
                jobj.put("upload_time",note.getStr("upload_time"));        
                jobj.put("upload_position",note.getStr("upload_position"));       
                jobj.put("res_type",note.getStr("res_type"));   
                jobj.put("modle_id",note.getStr("modle_id"));       
                jobj.put("tag_id",note.getStr("tag_id"));
                jarray.add(jobj);
            }
            jsonOjb.put("array",jarray);
        }
        if(jarray.size()==0) {
            return("nothing");
        }
        return jsonOjb.toString();
    }

    /**
     * 将笔记加入到收藏夹
     * @param note_id
     * @param tel
     * @param name
     * @return
     */
    public String addOneNoteToDirectory(String note_id, String tel, String name) {

        Collection collection = Collection.dao.findFirst("select * from tbl_collection where tel = ? and name = ? and note_id = ?",tel,name,note_id);

        if(collection==null) {

            //笔记表收藏数+1
            Note note = Note.dao.findByIdLoadColumns(note_id,"collection_num");
            int count = Integer.parseInt(note.getStr("collection_num"));

            Note.dao.findById(note_id).set("collection_num",++count).update();
            //收藏表加一条数据
            new Collection().set("note_id", note_id).set("tel", tel).set("name", name).save();
            return "1";
        }else {
            return "false";
        }

    }

    /**
     * 取消收藏
     * @param note_id
     * @param tel
     * @return
     */
    public String deleteOneNoteToDirectory(String note_id, String tel) {
        String sql = "delete from tbl_collection where note_id = '"+note_id+"' and tel = '"+tel+"'";
        int flag = Db.update(sql);
        if(flag>0) {
            Note note = Note.dao.findByIdLoadColumns(note_id,"collection_num");
            int count = Integer.parseInt(note.getStr("collection_num"));            
            int c = count - flag;
            if(c>=0) {
                Note.dao.findById(note_id).set("collection_num",c).update();
            }
            return "0";
        }else {
            return "false";
        }
     
    }

    /**
     * 删除收藏夹
     * @param tel
     * @param name
     * @return
     */
    public String deleteCollectionDirectory(String tel, String name) {
        int n = Db.update("delete from tbl_collection where tel = ? and name = ? ",tel,name);
        if(n>0) {
            return "0";
        }else {
            return "false";
        }
        
    }

   
    /**
     * 9图
     * @param str
     * @param node_id
     * @param in
     * @param out
     * @param fileType
     * @return
     */
    public boolean upLoadNineImg(String str, String node_id, InputStream in, OutputStream out, String fileType) {
        
        new Imgs().set("img_src", str+"."+fileType).set("node_id",node_id).save();
        
        //上传图片
        byte[] b = new byte[512];
        int n = -1;
        try {
            while((n=in.read(b))!=-1) {
                out.write(b,0,n);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return true;
    }
    
    /**
     * 首页图
     * @param str
     * @param node_id
     * @param in
     * @param out
     * @param fileType
     * @return
     */
    public boolean upLoadCoverImg(String str, String node_id, InputStream in, OutputStream out, String fileType,String res_type) {
        
        Note.dao.findById(node_id).set("cover_src", str+"."+fileType).set("res_type",res_type).update();
        
        //上传图片
        byte[] b = new byte[512];
        int n = -1;
        try {
            while((n=in.read(b))!=-1) {
                out.write(b,0,n);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return true;
    }

    /**
     * 发布笔记的文字
     * @param tel
     * @param titlle
     * @param content
     * @param upload_time
     * @param upload_position
     * @param res_type
     * @return
     */
    public String postNote(String tel, String titlle, String content, String upload_time, String upload_position) {
        Note note = new Note().set("tel",tel)
                .set("titlle",titlle)
                .set("content",content)
                .set("upload_time",upload_time)
                .set("upload_position",upload_position)
                .set("like_num",0)
                .set("collection_num",0)
                .set("comments_num",0);
        boolean b= note.save();
        String id = note.getInt("note_id")+"";
        if(b) {
            return id+"";
        }else {
            return "false";
        }
    }

    
}
