package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseOnlineTravel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineTravel extends BaseOnlineTravel<OnlineTravel> {
	public static final OnlineTravel dao = new OnlineTravel().dao();
}
