package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BasePlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plan extends BasePlan<Plan> {
	public static final Plan dao = new Plan().dao();
}
