package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseRoute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Route extends BaseRoute<Route> {
	public static final Route dao = new Route().dao();
}
