package journeyjourney.journey.model;

import journeyjourney.journey.model.base.BaseSonComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SonComment extends BaseSonComment<SonComment> {
	public static final SonComment dao = new SonComment().dao();
}
