package journeyjourney.journey.model;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Db;

import journeyjourney.journey.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User().dao();
	   
    /**
     * 登录
     * @param tel
     * @param pwd
     * @return
     */
    public boolean login(String tel, String pwd) {
        User user = User.dao.findByIdLoadColumns(tel, "pwd");
        if(user!=null&&user.getStr("pwd").equals(pwd)) {
            return true;
        }
        return false;
    }
    /**
     * 注册
     * @param tel
     * @param pwd
     * @return
     */
    public boolean register(String tel, String pwd) {
        User user = User.dao.findByIdLoadColumns(tel, "pwd");
        Date date = new Date();
        if(null==user) {
            
            boolean b = new User().set("tel",tel).set("pwd",pwd).set("name","用户"+date.getTime()).set("headSrc","original.jpg").save();
            return b;
        }
        return false;
    }
    
    /**
     * 上传头像
     * @param tel
     * @param in
     * @param out
     * @param type
     * @return
     */
    public boolean upLoadImg(String tel, InputStream in, OutputStream out,String type) {
        //上传图片
        byte[] b = new byte[512];
        int n = -1;
        try {
            while((n=in.read(b))!=-1) {
                out.write(b,0,n);
            }
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        //将图片名字添加到数据库
        User.dao.findById(tel).set("headSrc", tel+"."+type).update();
        return true;
    }
    
    /**
     * 我的界面
     * @param tel
     * @return
     */
    public String my(String tel) {
        
        User user = User.dao.findById(tel);
        //基本信息
        String name = user.getStr("name");
        String headSrc = "userImg/" + user.getStr("headSrc");
        String sex = "男";
        if(!(user.getStr("sex")+"").equals("null")) {
            sex = user.getStr("sex");
        }
        
        String intro = "签名";
        if(!(user.getStr("intro")+"").equals("null")) {
            intro = user.getStr("intro");
        }
        

        //关注数和粉丝数
        int follow = Db.queryInt("select count(*) from tbl_follow where fans_tel = '"+tel+"'");
        int fans = Db.queryInt("select count(*) from tbl_follow where follow_tel = '"+tel+"'");
        //被点赞数
        int loves = 0;
        List<Note> notes = Note.dao.find("select like_num from tbl_note where tel = '"+tel+"'");
        for(Note note : notes) {
            int count = note.getInt("like_num");
            loves = loves + count;
        }
        JSONObject jobj = new JSONObject();
        jobj.put("name",name);
        jobj.put("headSrc",headSrc);
        jobj.put("intro",intro);
        jobj.put("loves",loves);
        jobj.put("follow",follow);
        jobj.put("fans",fans);
        jobj.put("sex",sex);
        String json = jobj.toString();        
        return json;
    }
    /**
     * 完善个人信息
     * @param tel
     * @param name
     * @param sex
     * @param intro
     * @return
     */
    public String updateMy(String tel, String name, String sex, String intro) {
        Boolean b = User.dao.findById(tel).set("name",name).set("sex",sex).set("intro",intro).update();
        return b+"";
    }
    
    /**
     * 修改密码
     * @param tel
     * @param pwd
     * @return
     */
    public boolean updatePwd(String tel, String pwd) {
        Boolean flag = User.dao.findById(tel).set("pwd",pwd).update();
        return flag;
    }
    
    /**
     * 我的作品
     * @param tel
     * @return
     */
    public String myWorks(String tel,String count) {
        List<Note> lists = new ArrayList<Note>();
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();
        String str = "select * from tbl_note where tel = '"+tel+"' limit "+count+",5";
        List<Note> notes = Note.dao.find(str);
        for(Note noteee : notes) {
            String userTel = noteee.getStr("tel");
            String noteId = noteee.getStr("note_id");
            //用户信息
            User user = User.dao.findByIdLoadColumns(noteee.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            //转换json
            JSONObject jsonObj = new JSONObject();
            //用户信息
            jsonObj.put("userName", userName);
            jsonObj.put("userHeadSrc", userHeadSrc);
            //笔记信息
            jsonObj.put("note_id", noteee.getStr("note_id"));
            jsonObj.put("cover_src",  "coverImg/"+noteee.getStr("cover_src"));
            jsonObj.put("titlle", noteee.getStr("titlle"));
            jsonObj.put("like_num", noteee.getStr("like_num"));
            jArray.add(jsonObj);
        }
        if(jArray.size()==0) {
            return "1";
        }else {
            jobj.put("array", jArray);
        }
        
        return jobj.toString();
    }
    
    /**
     * 我的点赞
     * 当前用户点赞的用户的头像和用户名，和点赞作品的作品名
     * @param tel
     * @return
     */
    public String myLoveWork(String tel) {
        JSONObject jobj = new JSONObject();
        JSONArray jArray = new JSONArray();
        List<Love> lists = Love.dao.find("select * from tbl_love where note_id in (select note_id from tbl_note where tel = ?)",tel);
        for(Love love : lists) {
            JSONObject jjobj = new JSONObject();
            User user = User.dao.findByIdLoadColumns(love.getStr("tel"),"name,headSrc");
            String userName = user.getStr("name");
            String userHeadSrc = "userImg/" + user.getStr("headSrc");
            Note note000 = Note.dao.findFirst("select * from tbl_note where note_id = ?",love.getStr("note_id"));
            String name = note000.getStr("titlle");
            String src =   "coverImg/"+note000.getStr("cover_src");
            
            jjobj.put("userName", userName);
            jjobj.put("userHeadSrc", userHeadSrc);
            jjobj.put("name", name);
            jjobj.put("coverImg", src);
            jArray.add(jjobj);
        }
        jobj.put("array",jArray);
        
        
        return jobj.toString();
    }
    
    
    
    
    
}
