package journeyjourney.journey.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSonComment<M extends BaseSonComment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}

	public M setCommentsContent(java.lang.String commentsContent) {
		set("comments_content", commentsContent);
		return (M)this;
	}
	
	public java.lang.String getCommentsContent() {
		return getStr("comments_content");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setCommentsTime(java.util.Date commentsTime) {
		set("comments_time", commentsTime);
		return (M)this;
	}
	
	public java.util.Date getCommentsTime() {
		return get("comments_time");
	}

}
