package journeyjourney.journey.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseComments<M extends BaseComments<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setNoteId(java.lang.Integer noteId) {
		set("note_id", noteId);
		return (M)this;
	}
	
	public java.lang.Integer getNoteId() {
		return getInt("note_id");
	}

	public M setCommentsContent(java.lang.String commentsContent) {
		set("comments_content", commentsContent);
		return (M)this;
	}
	
	public java.lang.String getCommentsContent() {
		return getStr("comments_content");
	}

	public M setTel(java.lang.String tel) {
		set("tel", tel);
		return (M)this;
	}
	
	public java.lang.String getTel() {
		return getStr("tel");
	}

	public M setCommentsTime(java.lang.String commentsTime) {
		set("comments_time", commentsTime);
		return (M)this;
	}
	
	public java.lang.String getCommentsTime() {
		return getStr("comments_time");
	}

}
