package journeyjourney.journey.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseJourneyonline<M extends BaseJourneyonline<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public M setIntroduce(java.lang.String introduce) {
		set("introduce", introduce);
		return (M)this;
	}
	
	public java.lang.String getIntroduce() {
		return getStr("introduce");
	}

	public M setImageOne(java.lang.String imageOne) {
		set("image_one", imageOne);
		return (M)this;
	}
	
	public java.lang.String getImageOne() {
		return getStr("image_one");
	}

	public M setImageTwo(java.lang.String imageTwo) {
		set("image_two", imageTwo);
		return (M)this;
	}
	
	public java.lang.String getImageTwo() {
		return getStr("image_two");
	}

	public M setImageThree(java.lang.String imageThree) {
		set("image_three", imageThree);
		return (M)this;
	}
	
	public java.lang.String getImageThree() {
		return getStr("image_three");
	}

	public M setIntroduceOne(java.lang.String introduceOne) {
		set("introduce_one", introduceOne);
		return (M)this;
	}
	
	public java.lang.String getIntroduceOne() {
		return getStr("introduce_one");
	}

	public M setIntroduceTwo(java.lang.String introduceTwo) {
		set("introduce_two", introduceTwo);
		return (M)this;
	}
	
	public java.lang.String getIntroduceTwo() {
		return getStr("introduce_two");
	}

	public M setIntroduceThree(java.lang.String introduceThree) {
		set("introduce_three", introduceThree);
		return (M)this;
	}
	
	public java.lang.String getIntroduceThree() {
		return getStr("introduce_three");
	}

	public M setAddressOne(java.lang.String addressOne) {
		set("address_one", addressOne);
		return (M)this;
	}
	
	public java.lang.String getAddressOne() {
		return getStr("address_one");
	}

	public M setAddressTwo(java.lang.String addressTwo) {
		set("address_two", addressTwo);
		return (M)this;
	}
	
	public java.lang.String getAddressTwo() {
		return getStr("address_two");
	}

	public M setAddressThree(java.lang.String addressThree) {
		set("address_three", addressThree);
		return (M)this;
	}
	
	public java.lang.String getAddressThree() {
		return getStr("address_three");
	}

}
