package journeyjourney.journey.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFansTel(java.lang.String fansTel) {
		set("fans_tel", fansTel);
		return (M)this;
	}
	
	public java.lang.String getFansTel() {
		return getStr("fans_tel");
	}

	public M setFollowTel(java.lang.String followTel) {
		set("follow_tel", followTel);
		return (M)this;
	}
	
	public java.lang.String getFollowTel() {
		return getStr("follow_tel");
	}

}
